apiVersion: app/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replica: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      container:
      - image: nginx
        name: nginx